[project]
name = "educa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "coverage>=7.13.1",
    "django>=6.0.1",
    "django-unfold>=0.76.0",
    "pillow>=12.1.0",
    "python-decouple>=3.8",
]
